In [1]:
import os

import pandas

from helpers.data import MinioHelper, CalcHelper
import csv
from dotenv import load_dotenv
import polars

load_dotenv(override=True)

YEARS = ['2025', '2024']
BUCKET = 'cfb-stats-bucket'
SEASON = 'regular'
TYPE = 'players'

In [2]:
helper = MinioHelper(BUCKET)


data = helper.get_statistics(YEARS, SEASON, TYPE)

players/2025/regular/1/players-schedule-50e21fc0-78a5-491f-8c92-eb774c4cb190.parquet
players/2025/regular/10/players-schedule-d54b9fec-30b9-41ca-9feb-7dd3e759008c.parquet
players/2025/regular/11/players-schedule-b014c18d-ad9d-41a0-9275-807e12c71515.parquet
players/2025/regular/12/players-schedule-6f67df20-98f3-47ee-a973-f28f94096ee3.parquet
players/2025/regular/13/players-schedule-21f9ba34-a4d9-4581-ab96-368c1c9f38e8.parquet
players/2025/regular/14/players-schedule-c0863203-540c-4a24-a8fc-22991c5b9ce9.parquet
players/2025/regular/15/players-schedule-6a7c9dd4-0c6f-4fb2-805b-a83a5544bac8.parquet
players/2025/regular/16/players-schedule-4f57d8e5-005d-43c0-a41b-f77ac4bc63e7.parquet
players/2025/regular/2/players-schedule-bea8b45d-300a-4755-8884-879d4d3b64c1.parquet
players/2025/regular/3/players-schedule-cba70b2d-7286-4d37-861c-a14d163d23db.parquet
players/2025/regular/4/players-schedule-00a71c86-688b-4108-9dde-4e48d5d97529.parquet
players/2025/regular/5/players-schedule-3df2a486-8901-4509-85e2-6be3518edd10.parquet
players/2025/regular/6/players-schedule-f4c33719-3500-4cab-a837-837f63a999dd.parquet
players/2025/regular/7/players-schedule-eaeba3ed-3307-49e7-babd-1f53aaf4590e.parquet
players/2025/regular/8/players-schedule-378e4439-a7bd-4759-a6f0-d71cf4b6168f.parquet
players/2025/regular/9/players-schedule-0ab61546-c51d-404e-b2ed-4836f6c3c26b.parquet
players/2024/regular/1/players-schedule-df41e0ea-1245-4fa9-b225-fe95583f8c63.parquet
players/2024/regular/10/players-schedule-c3fed77f-75db-49b4-b932-44fd0aa7a84d.parquet
players/2024/regular/11/players-schedule-ca7cccc4-1c90-4661-b94f-2762fa8ae593.parquet
players/2024/regular/12/players-schedule-e2a01d10-525f-4ef6-bed9-e270857c673e.parquet
players/2024/regular/13/players-schedule-b9df63db-e58e-4622-9dd2-16f260a57ee7.parquet
players/2024/regular/14/players-schedule-cea06783-9b1c-436f-b030-65b16c75a5b7.parquet
players/2024/regular/15/players-schedule-83cf58c6-0c5c-4108-b15f-a0b253856009.parquet
players/2024/regular/16/players-schedule-7ada70b6-5bee-4230-85a3-d76f05bdb181.parquet
players/2024/regular/2/players-schedule-620df6f9-8189-4617-8e53-cd796043441c.parquet
players/2024/regular/3/players-schedule-1d7242b7-33ce-4fde-9040-0e2e90fca799.parquet
players/2024/regular/4/players-schedule-85978295-3449-43d0-ac96-172e08869fe3.parquet
players/2024/regular/5/players-schedule-5e373a9e-3b4b-427f-ac95-3859f876853d.parquet
players/2024/regular/6/players-schedule-970587dc-9d09-42bb-9f3c-aeecc640b1a1.parquet
players/2024/regular/7/players-schedule-bfd42e80-a515-435c-a055-48b8fe1b2bb6.parquet
players/2024/regular/8/players-schedule-a0be36b9-d8be-472c-861a-17bdc90a85ae.parquet
players/2024/regular/9/players-schedule-4ca1e5ae-aa72-434c-b90a-19265c274232.parquet

In [3]:
frame = polars.from_pandas(data)
frame.head(50)

shape: (50, 12)
┌──────┬──────┬───────────┬──────────────┬───┬─────────────┬───────────┬─────────────┬─────────────┐
│ week ┆ year ┆ game_type ┆ team         ┆ … ┆ statistic_v ┆ game_id   ┆ player_name ┆ player_url  │
│ ---  ┆ ---  ┆ ---       ┆ ---          ┆   ┆ alue        ┆ ---       ┆ ---         ┆ ---         │
│ i64  ┆ i64  ┆ i64       ┆ str          ┆   ┆ ---         ┆ str       ┆ str         ┆ str         │
│      ┆      ┆           ┆              ┆   ┆ f64         ┆           ┆             ┆             │
╞══════╪══════╪═══════════╪══════════════╪═══╪═════════════╪═══════════╪═════════════╪═════════════╡
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 14.0        ┆ 401756846 ┆ Rocco Becht ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 28.0        ┆ 401756846 ┆ Rocco Becht ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 183.0       ┆ 401756846 ┆ Rocco Becht ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 0.0         ┆ 401756846 ┆ Rocco Becht ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 2.0         ┆ 401756846 ┆ Rocco Becht ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
│ …    ┆ …    ┆ …         ┆ …            ┆ … ┆ …           ┆ …         ┆ …           ┆ …           │
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 1.0         ┆ 401756846 ┆ Dominic     ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆ Overby      ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 23.0        ┆ 401756846 ┆ Dominic     ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆ Overby      ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 2.0         ┆ 401756846 ┆ Carson      ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆ Hansen      ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 19.0        ┆ 401756846 ┆ Carson      ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆ Hansen      ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ Iowa State   ┆ … ┆ 0.0         ┆ 401756846 ┆ Carson      ┆ https://www │
│      ┆      ┆           ┆ Cyclones     ┆   ┆             ┆           ┆ Hansen      ┆ .espn.com/c │
│      ┆      ┆           ┆              ┆   ┆             ┆           ┆             ┆ ollege-f…   │
└──────┴──────┴───────────┴──────────────┴───┴─────────────┴───────────┴─────────────┴─────────────┘

In [4]:
lemon_frame = frame.filter(polars.col('player_name') =='Makai Lemon')

In [5]:
lemon_frame.head(1000)

shape: (244, 12)
┌──────┬──────┬───────────┬─────────────┬───┬──────────────┬───────────┬─────────────┬─────────────┐
│ week ┆ year ┆ game_type ┆ team        ┆ … ┆ statistic_va ┆ game_id   ┆ player_name ┆ player_url  │
│ ---  ┆ ---  ┆ ---       ┆ ---         ┆   ┆ lue          ┆ ---       ┆ ---         ┆ ---         │
│ i64  ┆ i64  ┆ i64       ┆ str         ┆   ┆ ---          ┆ str       ┆ str         ┆ str         │
│      ┆      ┆           ┆             ┆   ┆ f64          ┆           ┆             ┆             │
╞══════╪══════╪═══════════╪═════════════╪═══╪══════════════╪═══════════╪═════════════╪═════════════╡
│ 1    ┆ 2025 ┆ 2         ┆ USC Trojans ┆ … ┆ 7.0          ┆ 401752798 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ USC Trojans ┆ … ┆ 90.0         ┆ 401752798 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ USC Trojans ┆ … ┆ 0.0          ┆ 401752798 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ USC Trojans ┆ … ┆ 0.0          ┆ 401752798 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
│ 1    ┆ 2025 ┆ 2         ┆ USC Trojans ┆ … ┆ 26.0         ┆ 401752798 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
│ …    ┆ …    ┆ …         ┆ …           ┆ … ┆ …            ┆ …         ┆ …           ┆ …           │
│ 9    ┆ 2024 ┆ 2         ┆ USC Trojans ┆ … ┆ 3.0          ┆ 401628532 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
│ 9    ┆ 2024 ┆ 2         ┆ USC Trojans ┆ … ┆ 122.0        ┆ 401628532 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
│ 9    ┆ 2024 ┆ 2         ┆ USC Trojans ┆ … ┆ 0.0          ┆ 401628532 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
│ 9    ┆ 2024 ┆ 2         ┆ USC Trojans ┆ … ┆ 80.0         ┆ 401628532 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
│ 9    ┆ 2024 ┆ 2         ┆ USC Trojans ┆ … ┆ 0.0          ┆ 401628532 ┆ Makai Lemon ┆ https://www │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ .espn.com/c │
│      ┆      ┆           ┆             ┆   ┆              ┆           ┆             ┆ ollege-f…   │
└──────┴──────┴───────────┴─────────────┴───┴──────────────┴───────────┴─────────────┴─────────────┘